# Site settings
title: Archagon Was Here
html_title: <div class="title"><span class="name">Archagon</span> Was Here</div>
description: > # this means to ignore newlines until "baseurl:"
 Alexei's pile o'stuff, featuring writing on software development, travel, photography, and more.
baseurl: "" # the subpath of your site, e.g. /blog/ TODO: double slash
url: "http://beta-blog.archagon.net" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
timezone: America/Los_Angeles

# Social
email: archagon@archagon.net
twitter: archagon
github:  archagon
instagram: archagon
goodreads: 2196584-archagon
reddit: archagon
hackernews: archagon

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "index/:num/"
category_dir: "category"
category_layout: "index.html"
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-paginate-category

# Extra directories
image_dir: images
assets_dir: assets

# Extra files
default_icon: icon_default.png

exclude: [ blog.sublime-project, blog.sublime-workspace, Gemfile, Gemfile.lock, Rakefile, SETUP.txt, TOC.txt, TODO.txt, QUIRKS.txt, SNIPPETS.txt, PERMALINKS.txt, temp, raw, images/old-patterns, images/possible-patterns ]