# Site settings
title: Archagon Was Here (Jekyll Test)
email: archagon@archagon.net
description: > # this means to ignore newlines until "baseurl:"
  Archagon was here... or was he? Yes, he was. This is Alexei Baboulevitch's personal
  blog webspacehomepage, featuring writing on software development, travel, photography,
  and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.archagon.net" # the base hostname & protocol for your site
twitter_username: archagon
github_username:  archagon

# Build settings
markdown: kramdown

# Extra directories
image_dir: images

# Extra files
default_icon: icon_default.png
